# Generated by Django 5.2.4 on 2025-07-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GAURAV_lmsUser',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.IntegerField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('userType', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GAURAV_CourseUpload',
            fields=[
                ('courseUploadId', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=20)),
                ('courseDescription', models.CharField(max_length=50)),
                ('createdAt', models.DateField()),
                ('coursePlayList', models.CharField(max_length=10)),
                ('courseDuration', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GAURAV_COURSES.gaurav_lmsuser')),
            ],
        ),
    ]
